/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ziroby_jamis_Npc */

#ifndef _Included_com_ziroby_jamis_Npc
#define _Included_com_ziroby_jamis_Npc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ziroby_jamis_Npc
 * Method:    gen
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ziroby_jamis_Npc_gen
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
